### ISSUE TITLE
Question: Actual bulk/line/field size limits?

### ISSUE THREAD

**Issue by arcivanov** [logzio/fluentd-plugin-logzio#20]
Currently, bulk limit in the plugin is set to 1MB. Documentation [here](https://support.logz.io/hc/en-us/articles/209382509-How-do-I-upload-one-log-file-) seems to suggest that the maximum *file upload size* is 10MB.

Can someone please give definitive limits on the bulk sizes, line sizes and fields sizes? Please use exact bytes vs MB/MiB to avoid confusion.

**Comment by roiravhon** [comment]
Hey @arcivanov!
The maximum bulk size we support is 10MB, but we usually see better performance with lower sized bulks, hence the 1MB default. You can up that if you need, but i would leave some "spare" room and not get exactly to 10.

The rest of the log limitations are the same as Elasticsearch, for exact numbers please reach out to support (either via the in-app chat, or email support@logz.io)

**Comment by arcivanov** [comment]
Ok understood, I'll leave the bulk size in place in the plugin. Thanks!
