### ISSUE TITLE
Setting the global log_level to warn still shipping the info logs.

### ISSUE THREAD

**Issue by shetaksroc** [logzio/fluentd-plugin-logzio#27]
<system>
  log_level warn
</system>

**Comment by idohalevi** [comment]
@shetaksroc  We will need more details to understand the issue you are referring too...

**Comment by shetaksroc** [comment]
Yeah sure. 

My use case is to ship only the logs of level warn,error and fatal.  I was trying to filter out other lower level logs like info, debug etc.

But in order to achieve this, I had to set the global log_level to warn. But it didn't work as expected.
