### ISSUE TITLE
TOKEN param

### ISSUE THREAD

**Issue by ghjnut** [logzio/fluentd-plugin-logzio#28]
Is there any way we can have the `token` set as maybe and ENV variable or some other way to configure it? I usually don't like baking those into my images.

**Comment by jpelletier-dad** [comment]
Sorry, the "image" portion is irrelevant. I just happen to be working with docker.

**Comment by roiravhon** [comment]
@ghjnut Currently no, but you can wrap this container with another one that pass the token to the right place.

@idohalevi Lets add it to our feature list?

**Comment by idohalevi** [comment]
@ghjnut @roiravhon I will add it

**Comment by jpelletier-dad** [comment]
@idohalevi I was unaware of this
https://docs.fluentd.org/v0.12/articles/faq#how-can-i-use-environment-variables-to-configure-parameters-dynamically?
```
some_field "#{ENV['FOO_HOME']}"
```
which handles my use case

**Comment by jpelletier-dad** [comment]
As a side note, the s3 plugin has credentials as separate params which are redacted in the logs so it may still be useful to offer it as a separate config variable
```
  <match *.nodes.*>
    @type s3
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    ...
```
