### ISSUE TITLE
Accept gzipped bodies?

### ISSUE THREAD

**Issue by bakins** [logzio/fluentd-plugin-logzio#3]
It doesn't seem like the endpoint accepts gzipped request bodies.  This would save a good deal of bandwidth. Thoughts about supporting this?

**Comment by segalziv** [comment]
@bakins it is definitely on our roadmap, but unfortunately will not be available soon, as this requires some backend support on our end. 

So the options for the meantime are either use fluentd unzipped or move to File Beat which have compression and encryption.
