### ISSUE TITLE
Dynamic logzio type based on record fields

### ISSUE THREAD

**Issue by omerlh** [logzio/fluentd-plugin-logzio#30]
I would like to set the logzio type dynamically, based on a property in the record.
I tried something like that:
```
endpoint_url "${#{ENV['LOGZIO_URL']}?token=#{ENV['LOGZIO_TOKEN']}&type=#{record['custom_type']}"
```
But that failed:
```
undefined local variable or method `record' for £<Binding:0x00007f02fc64f770
```
Can you point me in the right direction?

**Comment by idohalevi** [comment]
@omerlh 
Hi Omer. Are you trying to send each log with a different type or you want all the logs to have the same type?

**Comment by omerlh** [comment]
I want to have different types for different services, based on a parameter the service sends in the log record.

**Comment by idohalevi** [comment]
@omerlh 
You can add a `type` field to the message.
https://docs.fluentd.org/v0.12/articles/filter-modify-apache

**Comment by omerlh** [comment]
And remove the type from the URL?

**Comment by idohalevi** [comment]
Yep :)

**Comment by omerlh** [comment]
Nice! I can confirm it's working :)
