### ISSUE TITLE
Update documentation to show plugin integration with `fluent/fluentd` docker container.

### ISSUE THREAD

**Issue by eyeezzi** [logzio/fluentd-plugin-logzio#32]
In addition to showing logz-specific configurations for the fluentd configuration file, it would be useful to give an example of a Dockerfile where this plugin is used. Something like this:

```
FROM fluent/fluentd:v1.4-2

# Use root account to use apk
USER root

# We need to install a plugin for logz.io output
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install \
        fluent-plugin-logzio \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.4.0/cache/*.gem

# Then copy-over our custom config file "fluentd.conf"
COPY fluentd.conf /fluentd/etc/
ENV FLUENTD_CONF="fluentd.conf"

USER fluent
```
It turns out the line `ENV FLUENTD_CONF="fluentd.conf"` is critical for anything to work...a lot of time was wasted in figuring that out since it was never mentioned anywhere on this repo's docs.

**Comment by idohalevi** [comment]
@eyeezzi 
I appreciate your comment, thank you. I feel like this is a docker/fluent related comment and not in the repo scope. You can check [this](https://github.com/logzio/logzio-k8s) repo for an example on how to use this plugin as part of a Dockerfile.
