### ISSUE TITLE
Latest versions of fluentd (1.9+) causes conflict with net-http-persistent dependency

### ISSUE THREAD

**Issue by dat-timfa** [logzio/fluentd-plugin-logzio#33]
In the latest versions of fluentd (1.9+) provided by banzaicloud (for consumption with logging-operator) gem is installing a newer version of net-http-persistent (3.0.0) which this plugin does not support.

What happens is both 2.9.4 (the version this plugin uses) and 3.0.0 of net-http-persistent are installed in the gems directory, and fluent-plugin-logzio attempts to use the latest instead of the one it's supposed to use.

To address short-term, I created a modified Dockerfile:

```
FROM banzaicloud/fluentd:v1.10.3-alpine-2+# install logz plugin

# Force re-install Logz plugin, using the older version of net-http-persistent
## The base image comes with both 2.9.4 and 3.0.0, and logz should be using 2.9.4 not 3.0.0 (else it breaks)
RUN gem install rdoc
RUN gem uninstall fluent-plugin-logzio --force
RUN gem uninstall net-http-persistent -v '>2.9.4' --force
RUN gem install fluent-plugin-logzio -v 0.0.20
USER fluent
```

But long-term ideally one of the two would happen:

- This plugin to use net-http-persistent version 3.0.0
- This plugin to specifically call the correct gem dependency that it uses, even when there are other versions available (I'm not a gem expert, not sure if this is possible with package dependencies here)

**Comment by tarokkk** [comment]
Do you plan on fixing this issue?

**Comment by Doron-Bargo** [comment]
Hi 
@dattim - thank you for notify us on this issue
@tarokkk - yes , we open a ticket for our development team to fix this issue.

**Comment by tarokkk** [comment]
Thank you for the follow-up!

**Comment by ekhaydarov** [comment]
@Doron-Bargo its been almost 6 months and there is no solution to this issue. Could we expect a timeline for this?
@tarokkk in the meantime would it be possible to update the dockerfile to enable this plugin to work with <3.x.x net-http-persistence dependency?

**Comment by jliao2011** [comment]
@Doron-Bargo is there an eta on when this issue will be resolved?

**Comment by Doron-Bargo** [comment]
Hi @jliao2011 
sorry it took us time
I assigned a developer to this issue and she is working on it now

**Comment by Doron-Bargo** [comment]
Hi @jliao2011 just to let you know the code is in final code review and will be released tomorrow

**Comment by mirii1994** [comment]
fluent-plugin-logzio v. 0.0.21 is out and should solve this issue #36 
Let us know if you're having further issues :)

**Comment by Doron-Bargo** [comment]
Hi @dat-timfa on March we released a version that fix this issue
Can you confirm?

Thanks
