### ISSUE TITLE
"You are not authorized with Logz.io! Token OK? dropping logs..." error effectively empty the buffers

### ISSUE THREAD

**Issue by ClemArt** [logzio/fluentd-plugin-logzio#34]
Hi there,
When we tried to integrate Fluentd with Logz.io we misused the *token* part of the *endpoint_url* parameter. That resulted in HTTP 401 responses from the logz.io endpoint.

As a result, a lot of `You are not authorized with Logz.io! Token OK? dropping logs...` came out in our container logs.
This message comes from the following code in the lib (line 143)
```
if response.code == '401'
       log.error "You are not authorized with Logz.io! Token OK? dropping logs..."
       should_retry = false
```

In the end, it appears the message is effectively pulled out of buffer, then dropped (not retried nor put back in the buffer). That way we lost a bunch of messages by the time we noticed the issue...

Is there a way to prevent the drop of the logs in case of such a misconfiguration ? Or even prevent dropping at all, and preserving in buffers all failed attempts ?
Maybe it's a behavior that could be set as a parameter of the plugin ?

Thank you in advance

**Comment by Doron-Bargo** [comment]
Hi @ClemArt 
Thank you for notify us on this issue.
I checked and it  doesn't make sense to drop the logs.
We will add a log error with the buffer that failed

**Comment by omerlh** [comment]
I just had a similar issue, and I wonder how we can monitor it. We have alert for `fluentd_output_status_num_errors` but I see it is 0 - although the plugin clearly has errors. 
What would you recommend us to do to monitor such issues? There are not a lot of logs so positive monitoring is hard (2 hours without any log is normal)
