### ISSUE TITLE
Is repo name wrong?

### ISSUE THREAD

**Issue by okkez** [logzio/fluentd-plugin-logzio#8]
This repository name is `fluentd-plugin-logzio`.
But in fluent-plugin-logzio.gemspes, 

```
s.homepage    = 'https://github.com/logzio/fluent-plugin-logzio'
```

This link is 404 not found for now.
I think `fluent-plugin-logzio` is proper for this repository name.
You can fix repository name and GitHub will redirect old repository to new repository.

Thanks!

**Comment by roiravhon** [comment]
Hey @okkez!
Can I ask why you think that fluent-plugin-logzio is a better name?

I prefer not to change the repo name, and just change the gemspec

**Comment by okkez** [comment]
@roiravhon Hi!
Because Almost all Fluentd plugins:

* repository name is started with `fluent-plugin-`
* gem name is started with `fluent-plugin-`
* repository name is equals to gem name

When users are looking for fluent plugins:
If repository name is started with `fluent-plugin-`, users can find the repository on GitHub easily.
If gem name is started with `fluent-plugin-`, users can find the gem on rubygems.org and gem search command.

```
$ gem search fluent-plugin- | wc -l
734
$ gem search fluentd-plugin- | wc -l
1

$ gem query -r "\Afluent-plugin-" | wc -l
731
$ gem query -r "\Afluentd-plugin-" | wc -l
1
```

**Comment by roiravhon** [comment]
Thanks for the detailed response :)

Good point you have there.
Will be fixed

**Comment by roiravhon** [comment]
Changed repo name.
Thanks for the feedback @okkez!

**Comment by okkez** [comment]
Thanks!
