### ISSUE TITLE
Log error message from server if shipping logs fail

### ISSUE THREAD

**Issue by n-rook** [logzio/fluentd-plugin-logzio#9]
Currently, if shipping logs fail, I only see this message.

Could not send your bulk after 3 tries. Sorry. Got HTTP 400

This makes it very difficult to debug what has gone wrong, since I cannot see any text error provided in the response from logz.io.

It would be better to log the message as well.

**Comment by roiravhon** [comment]
Indeed.
There are even 2 problems here, as we should not retry on 400 at all - just print the reason.
I'll fix that in the coming few days

**Comment by n-rook** [comment]
Cool, thank you! I'd contribute a PR, but... I don't know Ruby 😓

**Comment by roiravhon** [comment]
Hey @n-rook and thanks for reporting the issue!
Fixed, and pushed to ruby gems - version 0.0.9
